name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      # - name: Use Node.js 12.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     build: npm run build
      #     start: npm start
      #     wait-on: 'npx wait-on http://localhost:3000'
      #     config-file: cypress/config.json
      #     config: baseUrl=http://localhost:3000
      #   env:
      #     CI: true
      #     CYPRESS_CI: true

      - name: NPM install ğŸ“¦
        uses: bahmutov/npm-install@v1

      - name: Build site ğŸ—
        run: npm run deploy

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.CARBON_DEPLOY }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch